demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "localhost"
      user: "postgres"
      password: "postgres"
      port: 5433
      dbname: "postgres"
      schema : "public"
      threads: 4